export interface Landlord {
  id: number;
  username?: string;
  companyName?: string;
  rating: number;
  reviewsCount: number;
  pricePerHour: number;
  pricePerDay: number;
  avatar?: string;
  isVerified?: boolean;
  description?: string;
}

// Mock данные для тестирования (потом удалим)
export const mockLandlords: Landlord[] = [
  {
    id: 1,
    companyName: "Premium Auto Rental",
    username: "premium_auto",
    rating: 4.9,
    reviewsCount: 1245,
    pricePerHour: 25,
    pricePerDay: 180,
    isVerified: true,
    description: "Проверенный арендодатель",
  },
  {
    id: 2,
    companyName: "City Cars",
    username: "city_cars_kz",
    rating: 4.8,
    reviewsCount: 892,
    pricePerHour: 22,
    pricePerDay: 160,
    isVerified: true,
    description: "Быстрая выдача авто",
  },
  {
    id: 3,
    username: "Askar_Rent",
    rating: 4.7,
    reviewsCount: 543,
    pricePerHour: 20,
    pricePerDay: 145,
    isVerified: false,
    description: "Частный арендодатель",
  },
  {
    id: 4,
    companyName: "Elite Motors",
    username: "elite_motors",
    rating: 5.0,
    reviewsCount: 2105,
    pricePerHour: 30,
    pricePerDay: 220,
    isVerified: true,
    description: "Премиум сервис",
  },
  {
    id: 5,
    companyName: "Fast Rent",
    username: "fast_rent_24",
    rating: 4.6,
    reviewsCount: 678,
    pricePerHour: 18,
    pricePerDay: 130,
    isVerified: true,
    description: "Доступные цены",
  },
  {
    id: 6,
    username: "Nurlan_Auto",
    rating: 4.5,
    reviewsCount: 234,
    pricePerHour: 17,
    pricePerDay: 125,
    isVerified: false,
    description: "Индивидуальный подход",
  },
  {
    id: 7,
    companyName: "Luxury Drive",
    username: "luxury_drive_kz",
    rating: 4.9,
    reviewsCount: 1567,
    pricePerHour: 35,
    pricePerDay: 250,
    isVerified: true,
    description: "Роскошные автомобили",
  },
  {
    id: 8,
    companyName: "Budget Cars",
    username: "budget_cars",
    rating: 4.4,
    reviewsCount: 456,
    pricePerHour: 15,
    pricePerDay: 110,
    isVerified: true,
    description: "Эконом класс",
  },
  {
    id: 9,
    username: "Timur_Rental",
    rating: 4.7,
    reviewsCount: 389,
    pricePerHour: 19,
    pricePerDay: 140,
    isVerified: false,
    description: "Гибкие условия",
  },
  {
    id: 10,
    companyName: "Express Rent",
    username: "express_rent",
    rating: 4.8,
    reviewsCount: 923,
    pricePerHour: 23,
    pricePerDay: 170,
    isVerified: true,
    description: "Быстрое оформление",
  },
  {
    id: 11,
    companyName: "Top Auto",
    username: "top_auto_kz",
    rating: 4.9,
    reviewsCount: 1834,
    pricePerHour: 28,
    pricePerDay: 200,
    isVerified: true,
    description: "Лучшие предложения",
  },
  {
    id: 12,
    username: "Almat_Cars",
    rating: 4.6,
    reviewsCount: 512,
    pricePerHour: 21,
    pricePerDay: 155,
    isVerified: false,
    description: "Местный арендодатель",
  },
  {
    id: 13,
    companyName: "Smart Rent",
    username: "smart_rent_kz",
    rating: 4.7,
    reviewsCount: 745,
    pricePerHour: 24,
    pricePerDay: 175,
    isVerified: true,
    description: "Умный выбор",
  },
  {
    id: 14,
    companyName: "Gold Car Rental",
    username: "gold_car",
    rating: 5.0,
    reviewsCount: 1998,
    pricePerHour: 32,
    pricePerDay: 230,
    isVerified: true,
    description: "Золотой стандарт",
  },
  {
    id: 15,
    username: "Dias_Rent",
    rating: 4.5,
    reviewsCount: 298,
    pricePerHour: 16,
    pricePerDay: 120,
    isVerified: false,
    description: "Надежный сервис",
  },
  {
    id: 16,
    companyName: "Pro Rental",
    username: "pro_rental_kz",
    rating: 4.8,
    reviewsCount: 1123,
    pricePerHour: 26,
    pricePerDay: 190,
    isVerified: true,
    description: "Профессиональный подход",
  },
  {
    id: 17,
    companyName: "Easy Drive",
    username: "easy_drive",
    rating: 4.6,
    reviewsCount: 634,
    pricePerHour: 20,
    pricePerDay: 150,
    isVerified: true,
    description: "Легко и просто",
  },
  {
    id: 18,
    username: "Marat_Auto",
    rating: 4.4,
    reviewsCount: 187,
    pricePerHour: 14,
    pricePerDay: 105,
    isVerified: false,
    description: "Самые низкие цены",
  },
  {
    id: 19,
    companyName: "VIP Motors",
    username: "vip_motors_kz",
    rating: 5.0,
    reviewsCount: 2567,
    pricePerHour: 40,
    pricePerDay: 280,
    isVerified: true,
    description: "VIP обслуживание",
  },
  {
    id: 20,
    companyName: "Comfort Rent",
    username: "comfort_rent",
    rating: 4.7,
    reviewsCount: 876,
    pricePerHour: 22,
    pricePerDay: 165,
    isVerified: true,
    description: "Комфортная аренда",
  },
  {
    id: 21,
    username: "Yerlan_Cars",
    rating: 4.5,
    reviewsCount: 345,
    pricePerHour: 18,
    pricePerDay: 135,
    isVerified: false,
    description: "Честные цены",
  },
  {
    id: 22,
    companyName: "Prime Auto",
    username: "prime_auto_kz",
    rating: 4.9,
    reviewsCount: 1456,
    pricePerHour: 29,
    pricePerDay: 210,
    isVerified: true,
    description: "Первоклассный сервис",
  },
  {
    id: 23,
    companyName: "Quick Rent",
    username: "quick_rent",
    rating: 4.6,
    reviewsCount: 589,
    pricePerHour: 19,
    pricePerDay: 142,
    isVerified: true,
    description: "Быстрая аренда",
  },
  {
    id: 24,
    username: "Baurzhan_Auto",
    rating: 4.4,
    reviewsCount: 223,
    pricePerHour: 15,
    pricePerDay: 115,
    isVerified: false,
    description: "Выгодные условия",
  },
  {
    id: 25,
    companyName: "Star Rental",
    username: "star_rental_kz",
    rating: 4.8,
    reviewsCount: 1289,
    pricePerHour: 27,
    pricePerDay: 195,
    isVerified: true,
    description: "Звездный сервис",
  },
  {
    id: 26,
    companyName: "Metro Cars",
    username: "metro_cars",
    rating: 4.7,
    reviewsCount: 734,
    pricePerHour: 21,
    pricePerDay: 158,
    isVerified: true,
    description: "Удобное расположение",
  },
  {
    id: 27,
    username: "Serik_Rent",
    rating: 4.6,
    reviewsCount: 412,
    pricePerHour: 17,
    pricePerDay: 128,
    isVerified: false,
    description: "Индивидуальные условия",
  },
  {
    id: 28,
    companyName: "Mega Rent",
    username: "mega_rent_kz",
    rating: 4.9,
    reviewsCount: 1678,
    pricePerHour: 31,
    pricePerDay: 225,
    isVerified: true,
    description: "Мега предложения",
  },
  {
    id: 29,
    companyName: "Drive Plus",
    username: "drive_plus",
    rating: 4.5,
    reviewsCount: 567,
    pricePerHour: 20,
    pricePerDay: 148,
    isVerified: true,
    description: "Драйв с комфортом",
  },
  {
    id: 30,
    username: "Ruslan_Auto",
    rating: 4.3,
    reviewsCount: 156,
    pricePerHour: 13,
    pricePerDay: 100,
    isVerified: false,
    description: "Доступная аренда",
  },
];
